version: '3.8'

services:
  sharex-manager:
    build:
      context: .
      target: runner
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL:-http://localhost:3000}
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./config:/app/config
      - uploads_data:/app/uploads
      - config_data:/app/config

volumes:
  uploads_data:
    driver: local
  config_data:
    driver: local 