version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sharex-manager
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
    volumes:
      - ./uploads:/app/uploads
      - ./config:/app/config
      - uploads_data:/app/uploads
      - config_data:/app/config

volumes:
  uploads_data:
    driver: local
  config_data:
    driver: local 